import { useEffect, useRef, useState } from 'react';
import { Check, X, Mail, RefreshCw, AlertCircle } from 'lucide-react';

const questions = [
  {
    id: 1,
    text: 'Is the system deployed at scale?',
    weight: 1,
  },
  {
    id: 2,
    text: 'Are harms difficult to reverse?',
    weight: 1,
  },
  {
    id: 3,
    text: 'Is there limited public transparency?',
    weight: 1,
  },
  {
    id: 4,
    text: 'Are welfare tradeoffs baked into the business model?',
    weight: 1,
  },
  {
    id: 5,
    text: 'Is there weak oversight or no appeal process?',
    weight: 1,
  },
  {
    id: 6,
    text: 'Are animals treated as replaceable inputs?',
    weight: 1,
  },
];

const stageResults = [
  {
    minScore: 0,
    maxScore: 1,
    stage: '01',
    stageName: 'LOW RISK',
    color: 'stage-low',
    bgColor: 'bg-stage-low',
    actions: ['Map current AI uses', 'Establish transparency register'],
  },
  {
    minScore: 2,
    maxScore: 3,
    stage: '02',
    stageName: 'MODERATE RISK',
    color: 'stage-moderate',
    bgColor: 'bg-stage-moderate',
    actions: ['Introduce welfare audits', 'Set procurement red lines'],
  },
  {
    minScore: 4,
    maxScore: 5,
    stage: '03',
    stageName: 'HIGH RISK',
    color: 'stage-high',
    bgColor: 'bg-stage-high',
    actions: ['Enforce hard limits', 'Enable whistleblowing channels'],
  },
  {
    minScore: 6,
    maxScore: 6,
    stage: '04',
    stageName: 'CRITICAL RISK',
    color: 'stage-critical',
    bgColor: 'bg-stage-critical',
    actions: ['Emergency suspension', 'Restorative measures'],
  },
];

export function AssessmentSection() {
  const sectionRef = useRef<HTMLDivElement>(null);
  const [isVisible, setIsVisible] = useState(false);
  const [answers, setAnswers] = useState<Record<number, boolean | null>>({});
  const [showResult, setShowResult] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
          observer.disconnect();
        }
      },
      { threshold: 0.1 }
    );

    if (sectionRef.current) {
      observer.observe(sectionRef.current);
    }

    return () => observer.disconnect();
  }, []);

  const handleAnswer = (questionId: number, answer: boolean) => {
    setAnswers((prev) => ({ ...prev, [questionId]: answer }));
    
    // Check if all questions are answered
    const newAnswers = { ...answers, [questionId]: answer };
    const answeredCount = Object.values(newAnswers).filter((a) => a !== null).length;
    if (answeredCount === questions.length) {
      setShowResult(true);
    }
  };

  const resetAssessment = () => {
    setAnswers({});
    setShowResult(false);
  };

  const score = Object.values(answers).filter((a) => a === true).length;
  const result = stageResults.find((r) => score >= r.minScore && score <= r.maxScore) || stageResults[0];

  const generateEmailBody = () => {
    const actions = result.actions.join(' • ');
    return encodeURIComponent(
      `AI Risk Clock Assessment Results\n\nScore: ${score}/${questions.length}\nStage: ${result.stage} - ${result.stageName}\n\nRecommended Actions:\n${actions}\n\n---\nGenerated by AI Risk Clock for Animals`
    );
  };

  return (
    <div
      ref={sectionRef}
      className="relative w-full min-h-screen bg-[#0B0F17] py-20 lg:py-32"
    >
      {/* Background Pattern */}
      <div className="absolute inset-0 opacity-5">
        <div className="absolute inset-0" style={{
          backgroundImage: `radial-gradient(circle at 1px 1px, #FF6A3D 1px, transparent 0)`,
          backgroundSize: '40px 40px',
        }} />
      </div>

      <div className="relative z-10 w-full px-6 lg:px-12">
        <div className="flex flex-col lg:flex-row gap-12 lg:gap-16">
          {/* Left: Title & Intro */}
          <div
            className={`lg:w-1/3 transition-all duration-700 ${
              isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'
            }`}
          >
            <h2 className="font-display font-bold text-4xl lg:text-5xl text-[#F2F5FA] mb-6">
              QUICK ASSESSMENT
            </h2>
            <p className="text-[#A7B1C8] text-base leading-relaxed mb-8">
              Answer six questions to see where your AI use case sits on the clock—and what to do next.
            </p>

            {/* Progress Indicator */}
            <div className="flex items-center gap-2 mb-4">
              <span className="font-mono text-sm text-[#A7B1C8]">
                {Object.values(answers).filter((a) => a !== null).length} / {questions.length}
              </span>
              <div className="flex-1 h-1 bg-white/10 rounded-full overflow-hidden">
                <div
                  className="h-full bg-[#FF6A3D] transition-all duration-500"
                  style={{
                    width: `${(Object.values(answers).filter((a) => a !== null).length / questions.length) * 100}%`,
                  }}
                />
              </div>
            </div>

            {/* Info Box */}
            <div className="card-sharp p-4 mt-8">
              <div className="flex items-start gap-3">
                <AlertCircle className="w-5 h-5 text-[#FF6A3D] flex-shrink-0 mt-0.5" />
                <p className="text-xs text-[#A7B1C8]">
                  This assessment is for educational purposes. For comprehensive risk evaluation, consult with AI ethics and animal welfare experts.
                </p>
              </div>
            </div>
          </div>

          {/* Right: Checklist */}
          <div
            className={`lg:w-2/3 transition-all duration-700 delay-200 ${
              isVisible ? 'opacity-100 translate-x-0' : 'opacity-0 translate-x-12'
            }`}
          >
            <div className="card-sharp p-6 lg:p-8">
              {/* Questions */}
              <div className="space-y-4">
                {questions.map((question, index) => (
                  <div
                    key={question.id}
                    className={`p-4 border border-white/10 hover:border-white/20 transition-all duration-300 ${
                      answers[question.id] === true ? 'bg-[#FF6A3D]/10 border-[#FF6A3D]/30' : ''
                    } ${answers[question.id] === false ? 'bg-white/5' : ''}`}
                    style={{ animationDelay: `${index * 50}ms` }}
                  >
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex items-start gap-4">
                        <span className="font-mono text-sm text-[#A7B1C8] flex-shrink-0">
                          {String(question.id).padStart(2, '0')}
                        </span>
                        <p className="text-[#F2F5FA] text-sm lg:text-base">
                          {question.text}
                        </p>
                      </div>
                      <div className="flex items-center gap-2 flex-shrink-0">
                        <button
                          onClick={() => handleAnswer(question.id, true)}
                          className={`w-8 h-8 flex items-center justify-center border transition-all duration-300 ${
                            answers[question.id] === true
                              ? 'bg-[#FF6A3D] border-[#FF6A3D] text-white'
                              : 'border-white/20 text-[#A7B1C8] hover:border-[#FF6A3D]/50'
                          }`}
                        >
                          <Check className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleAnswer(question.id, false)}
                          className={`w-8 h-8 flex items-center justify-center border transition-all duration-300 ${
                            answers[question.id] === false
                              ? 'bg-white/20 border-white/40 text-white'
                              : 'border-white/20 text-[#A7B1C8] hover:border-white/40'
                          }`}
                        >
                          <X className="w-4 h-4" />
                        </button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              {/* Result Banner */}
              {showResult && (
                <div
                  className={`mt-8 p-6 ${result.bgColor} border ${result.color.replace('stage-', 'border-stage-')} transition-all duration-500`}
                >
                  <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
                    <div>
                      <div className="flex items-center gap-3 mb-2">
                        <span className="font-mono text-sm text-[#A7B1C8]">Your score:</span>
                        <span className="font-display font-bold text-2xl text-[#F2F5FA]">
                          {score}/{questions.length}
                        </span>
                        <span className={`font-display font-bold text-lg ${result.color}`}>
                          {result.stageName}
                        </span>
                      </div>
                      <p className="text-sm text-[#F2F5FA]/80">
                        Next steps: {result.actions.join(' • ')}
                      </p>
                    </div>
                    <div className="flex items-center gap-3">
                      <button
                        onClick={resetAssessment}
                        className="flex items-center gap-2 px-4 py-2 border border-white/20 text-[#A7B1C8] hover:text-[#F2F5FA] hover:border-white/40 transition-all"
                      >
                        <RefreshCw className="w-4 h-4" />
                        <span>Reset</span>
                      </button>
                      <a
                        href={`mailto:?subject=AI Risk Clock Assessment Results&body=${generateEmailBody()}`}
                        className="flex items-center gap-2 px-4 py-2 bg-[#FF6A3D] text-white hover:bg-[#FF6A3D]/90 transition-colors"
                      >
                        <Mail className="w-4 h-4" />
                        <span>Email results</span>
                      </a>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
